import type { Calendar } from "./models";
import { DayType } from "./models";

export default [
	{
		name: "Vendémiaire",
		image: "vendemiaire.jpg",
		description: "Période des vendanges",
		notes: [
			{
				title: 'Histoire - Création',
				content: "Le calendrier républicain a été adopté par décret de la Convention nationale le <time>15 vendémiaire an II</time> (6 octobre 1793). Le début de l'ère républicaine a lui été fixé rétroactivement au 22 septembre 1792, jour de l'équinoxe d'automne et de la proclamation de la République.",
			},
			{
				title: 'Citation - Charles-Gilbert Romme',
				content: `<blockquote>"Le <time>22 septembre</time> fut décrété le premier de la République, et le même jour à 9 heures 18 minutes 30 secondes du matin le soleil est arrivé à l'équinoxe vrai, en entrant dans le signe de la balance. Ainsi l'égalité des jours aux nuits était marquée dans le ciel, au moment même où l'égalité civile et morale était proclamée par les représentants du peuple français comme le fondement sacré de son nouveau gouvernement"</blockquote>`,
			},
			{
				title: 'À propos de vendémiaire',
				content: "Cette période correspond à la saison des vendanges dans l'hémisphère nord. Bien que ses concepteurs l'aient voulu universel, le calendrier républicain était très influencé par le monde rural français.",
			},
		],
		days: [
			{
				day: 1,
				name: "Raisin",
				type: DayType.Fruit,
				wikipedia: "https://fr.wikipedia.org/wiki/Raisin",
			},
			{
				day: 2,
				name: "Safran",
				type: DayType.Fleur,
				wikipedia: "https://fr.wikipedia.org/wiki/Safran_(épice)",
			},
			{
				day: 3,
				name: "Châtaigne",
				type: DayType.Fruit,
				wikipedia: "https://fr.wikipedia.org/wiki/Châtaigne",
			},
			{
				day: 4,
				name: "Colchique",
				type: DayType.Fleur,
				wikipedia: "https://fr.wikipedia.org/wiki/Colchique",
			},
			{
				day: 5,
				name: "Cheval",
				type: DayType.Mammifère,
				wikipedia: "https://fr.wikipedia.org/wiki/Cheval",
			},
			{
				day: 6,
				name: "Balsamine",
				type: DayType.Fleur,
				wikipedia: "https://fr.wikipedia.org/wiki/Balsaminaceae",
			},
			{
				day: 7,
				name: "Carotte",
				type: DayType.Racine,
				wikipedia: "https://fr.wikipedia.org/wiki/Carotte",
			},
			{
				day: 8,
				name: "Amarante",
				type: DayType.Fleur,
				wikipedia: "https://fr.wikipedia.org/wiki/Amarante_(plante)",
			},
			{
				day: 9,
				name: "Panais",
				type: DayType.Racine,
				wikipedia: "https://fr.wikipedia.org/wiki/Panais",
			},
			{
				day: 10,
				name: "Cuve",
				type: DayType.Outil,
				wikipedia: "https://fr.wikipedia.org/wiki/Cuve",
			},
			{
				day: 11,
				name: "Pomme de terre",
				type: DayType.Racine,
				wikipedia: "https://fr.wikipedia.org/wiki/Pomme_de_terre",
			},
			{
				day: 12,
				name: "Immortelle",
				type: DayType.Fleur,
				wikipedia: "https://fr.wikipedia.org/wiki/Immortelle_commune",
			},
			{
				day: 13,
				name: "Potiron",
				type: DayType.Fruit,
				wikipedia: "https://fr.wikipedia.org/wiki/Potiron",
			},
			{
				day: 14,
				name: "Réséda",
				type: DayType.Fleur,
				wikipedia: "https://fr.wikipedia.org/wiki/Réséda",
			},
			{
				day: 15,
				name: "Âne",
				type: DayType.Mammifère,
				wikipedia: "https://fr.wikipedia.org/wiki/Âne",
			},
			{
				day: 16,
				name: "Belle-de-nuit",
				type: DayType.Fleur,
				wikipedia: "https://fr.wikipedia.org/wiki/Mirabilis_jalapa",
			},
			{
				day: 17,
				name: "Citrouille",
				type: DayType.Fruit,
				wikipedia: "https://fr.wikipedia.org/wiki/Citrouille",
			},
			{
				day: 18,
				name: "Sarrasin",
				type: DayType.Céréale,
				wikipedia: "https://fr.wikipedia.org/wiki/Sarrasin_commun",
			},
			{
				day: 19,
				name: "Tournesol",
				type: DayType.Fleur,
				wikipedia: "https://fr.wikipedia.org/wiki/Tournesol",
			},
			{
				day: 20,
				name: "Pressoir",
				type: DayType.Outil,
				wikipedia: "https://fr.wikipedia.org/wiki/Pressoir",
			},
			{
				day: 21,
				name: "Chanvre",
				type: DayType.Végétal,
				wikipedia: "https://fr.wikipedia.org/wiki/Chanvre",
			},
			{
				day: 22,
				name: "Pêche",
				type: DayType.Fruit,
				wikipedia: "https://fr.wikipedia.org/wiki/Pêche_(fruit)",
			},
			{
				day: 23,
				name: "Navet",
				type: DayType.Racine,
				wikipedia: "https://fr.wikipedia.org/wiki/Navet",
			},
			{
				day: 24,
				name: "Amaryllis",
				type: DayType.Fleur,
				wikipedia: "https://fr.wikipedia.org/wiki/Amaryllis_(plante)",
			},
			{
				day: 25,
				name: "Bœuf",
				type: DayType.Mammifère,
				wikipedia: "https://fr.wikipedia.org/wiki/Bos_taurus",
			},
			{
				day: 26,
				name: "Aubergine",
				type: DayType.Fruit,
				wikipedia: "https://fr.wikipedia.org/wiki/Aubergine",
			},
			{
				day: 27,
				name: "Piment",
				type: DayType.Fruit,
				wikipedia: "https://fr.wikipedia.org/wiki/Piment",
			},
			{
				day: 28,
				name: "Tomate",
				type: DayType.Fruit,
				wikipedia: "https://fr.wikipedia.org/wiki/Tomate",
			},
			{
				day: 29,
				name: "Orge",
				type: DayType.Céréale,
				wikipedia: "https://fr.wikipedia.org/wiki/Orge_commune",
			},
			{
				day: 30,
				name: "Tonneau",
				type: DayType.Outil,
				wikipedia: "https://fr.wikipedia.org/wiki/Tonneau_(récipient)",
			},
		],
	},
	{
		name: "Brumaire",
		image: "brumaire.jpg",
		description: "Période des brumes et des brouillards",
		notes: [
			{
				title: 'Choix techniques - Rupture avec la religion',
				content: `Le calendrier avait pour volonté de rompre avec les origines religieuses et donc monarchiques du calendrier Grégorien. Les changements sont considérables:
<ul>
<li>Changement d'ère, l'année 0 n'a plus comme référence la naissance du Christ, mais celle de la République française.</li>
<li>Les jours ne sont plus associés à des saints, mais à des mots provenant de la nature et du monde rural.</li>
<li>Les fêtes chômées liées au christianisme sont supprimées, et sont rapidement remplacées par les fêtes révolutionnaires.</li>
</ul>`
			},
			{
				title: 'Anecdote - 18 Brumaire',
				content: "Ce mois a donné son nom au coup d'État, intervenu le <time>18 brumaire an VIII</time> (9 novembre 1799), qui porta le général Napoléon Bonaparte au pouvoir en France. On parle dans ce cas du 18 Brumaire, nom propre, avec majuscule à la deuxième partie du nom, mais également de Brumaire, là aussi avec une majuscule, pour distinguer du nom du mois en général.",
			},
			{
				title: 'Suffixe saisonnier',
				content: 'Tous les mois d\'automne se terminent par le suffixe "-aire" du suffixe adjectival latin "-arius".'
			}
		],
		days: [
			{
				day: 1,
				name: "Pomme",
				type: DayType.Fruit,
				wikipedia: "https://fr.wikipedia.org/wiki/Pomme",
			},
			{
				day: 2,
				name: "Céleri",
				type: DayType.Végétal,
				wikipedia: "https://fr.wikipedia.org/wiki/Céleri",
			},
			{
				day: 3,
				name: "Poire",
				type: DayType.Fruit,
				wikipedia: "https://fr.wikipedia.org/wiki/Poire",
			},
			{
				day: 4,
				name: "Betterave",
				type: DayType.Racine,
				wikipedia: "https://fr.wikipedia.org/wiki/Betterave",
			},
			{
				day: 5,
				name: "Oie",
				type: DayType.Oiseau,
				wikipedia: "https://fr.wikipedia.org/wiki/Oie",
			},
			{
				day: 6,
				name: "Héliotrope",
				type: DayType.Fleur,
				wikipedia: "https://fr.wikipedia.org/wiki/Héliotrope",
			},
			{
				day: 7,
				name: "Figue",
				type: DayType.Fruit,
				wikipedia: "https://fr.wikipedia.org/wiki/Figue",
			},
			{
				day: 8,
				name: "Scorsonère",
				type: DayType.Racine,
				wikipedia: "https://fr.wikipedia.org/wiki/Scorsonère",
			},
			{
				day: 9,
				name: "Alisier",
				type: DayType.Végétal,
				wikipedia: "https://fr.wikipedia.org/wiki/Sorbus_torminalis",
			},
			{
				day: 10,
				name: "Charrue",
				type: DayType.Outil,
				wikipedia: "https://fr.wikipedia.org/wiki/Charrue",
			},
			{
				day: 11,
				name: "Salsifis",
				type: DayType.Racine,
				wikipedia: "https://fr.wikipedia.org/wiki/Salsifis",
			},
			{
				day: 12,
				name: "Mâcre",
				type: DayType.Végétal,
				wikipedia: "https://fr.wikipedia.org/wiki/Mâcre_nageante",
			},
			{
				day: 13,
				name: "Topinambour",
				type: DayType.Racine,
				wikipedia: "https://fr.wikipedia.org/wiki/Topinambour",
			},
			{
				day: 14,
				name: "Endive",
				type: DayType.Végétal,
				wikipedia: "https://fr.wikipedia.org/wiki/Endive",
			},
			{
				day: 15,
				name: "Dindon",
				type: DayType.Oiseau,
				wikipedia: "https://fr.wikipedia.org/wiki/Dinde",
			},
			{
				day: 16,
				name: "Chervis",
				type: DayType.Racine,
				wikipedia: "https://fr.wikipedia.org/wiki/Chervis",
			},
			{
				day: 17,
				name: "Cresson",
				type: DayType.Racine,
				wikipedia: "https://fr.wikipedia.org/wiki/Cresson_de_fontaine",
			},
			{
				day: 18,
				name: "Dentelaire",
				type: DayType.Fleur,
				wikipedia: "https://fr.wikipedia.org/wiki/Plumbago",
			},
			{
				day: 19,
				name: "Grenade",
				type: DayType.Fruit,
				wikipedia: "https://fr.wikipedia.org/wiki/Grenade_(fruit)",
			},
			{
				day: 20,
				name: "Herse",
				type: DayType.Outil,
				wikipedia: "https://fr.wikipedia.org/wiki/Herse_(agriculture)",
			},
			{
				day: 21,
				name: "Bacchante",
				type: DayType.Végétal,
				wikipedia: "https://fr.wikipedia.org/wiki/Baccharis_halimifolia",
			},
			{
				day: 22,
				name: "Azerole",
				type: DayType.Fruit,
				wikipedia: "https://fr.wikipedia.org/wiki/Crataegus_azarolus",
			},
			{
				day: 23,
				name: "Garance",
				type: DayType.Végétal,
				wikipedia: "https://fr.wikipedia.org/wiki/Garance_des_teinturiers",
			},
			{
				day: 24,
				name: "Orange",
				type: DayType.Fruit,
				wikipedia: "https://fr.wikipedia.org/wiki/Orange_(fruit)",
			},
			{
				day: 25,
				name: "Faisan",
				type: DayType.Oiseau,
				wikipedia: "https://fr.wikipedia.org/wiki/Faisan",
			},
			{
				day: 26,
				name: "Pistache",
				type: DayType.Fruit,
				wikipedia: "https://fr.wikipedia.org/wiki/Pistache",
			},
			{
				day: 27,
				name: "Macjonc",
				type: DayType.Fleur,
				wikipedia: "https://fr.wikipedia.org/wiki/Gesse_tubéreuse",
			},
			{
				day: 28,
				name: "Coing",
				type: DayType.Fruit,
				wikipedia: "https://fr.wikipedia.org/wiki/Coing",
			},
			{
				day: 29,
				name: "Cormier",
				type: DayType.Végétal,
				wikipedia: "https://fr.wikipedia.org/wiki/Cormier",
			},
			{
				day: 30,
				name: "Rouleau",
				type: DayType.Outil,
				wikipedia: "https://fr.wikipedia.org/wiki/Rouleau_agricole",
			},
		],
	},
	{
		name: "Frimaire",
		image: "frimaire.jpg",
		description: "Période des froids",
		notes: [
			{
				title: 'Choix techniques - Système décimal',
				content: 'Comme pour le système métrique adopté à la même période, le calendrier républicain a des fondements scientifique et rationnels. Les révolutionnaires français décident d\'utiliser un système basé sur le système décimal. Les semaines sont remplacées par des décades de dix jours. Une année est alors composée de douze mois eux mêmes composés de trois décades. Cette année est ensuite complétée par cinq jours complémentaires, ou six pour les années sextiles. S\'y ajoute, en outre, une division décimale des jours, des heures et des minutes.',
			},
			// {
			// 	title: 'Anecdote',
			// 	content: 'C\'est en frimaire an II (novembre-décembre 1793) que fut votée la "Loi des suspects" et que la Terreur atteignit son apogée. Le décret du 4 frimaire an II (24 novembre 1793) organisa le gouvernement révolutionnaire, renforçant le pouvoir du Comité de salut public. Cette période marqua l\'un des moments les plus sombres de la Révolution française.',
			// },
			{
				title: 'Étymologie',
				content: 'Frimaire dérive du latin "frigus" et de l\'ancien français "frimas" (gelée blanche, givre).',
			},

		],
		days: [
			{
				day: 1,
				name: "Raiponce",
				type: DayType.Végétal,
				wikipedia: "https://fr.wikipedia.org/wiki/Raiponce_(plante)",
			},
			{
				day: 2,
				name: "Turneps",
				type: DayType.Racine,
				wikipedia: "https://fr.wikipedia.org/wiki/Brassica_rapa",
			},
			{
				day: 3,
				name: "Chicorée",
				type: DayType.Végétal,
				wikipedia: "https://fr.wikipedia.org/wiki/Chicorée",
			},
			{
				day: 4,
				name: "Nèfle",
				type: DayType.Fruit,
				wikipedia: "https://fr.wikipedia.org/wiki/Nèfle",
			},
			{
				day: 5,
				name: "Cochon",
				type: DayType.Mammifère,
				wikipedia: "https://fr.wikipedia.org/wiki/Porc",
			},
			{
				day: 6,
				name: "Mâche",
				type: DayType.Végétal,
				wikipedia: "https://fr.wikipedia.org/wiki/Valerianella_locusta",
			},
			{
				day: 7,
				name: "Chou-fleur",
				type: DayType.Végétal,
				wikipedia: "https://fr.wikipedia.org/wiki/Chou-fleur",
			},
			{
				day: 8,
				name: "Miel",
				type: DayType.DérivéVégétal,
				wikipedia: "https://fr.wikipedia.org/wiki/Miel",
			},
			{
				day: 9,
				name: "Genièvre",
				type: DayType.Fruit,
				wikipedia: "https://fr.wikipedia.org/wiki/Juniperus_communis",
			},
			{
				day: 10,
				name: "Pioche",
				type: DayType.Outil,
				wikipedia: "https://fr.wikipedia.org/wiki/Pioche",
			},
			{
				day: 11,
				name: "Cire",
				type: DayType.DérivéVégétal,
				wikipedia: "https://fr.wikipedia.org/wiki/Cire",
			},
			{
				day: 12,
				name: "Raifort",
				type: DayType.Racine,
				wikipedia: "https://fr.wikipedia.org/wiki/Raifort",
			},
			{
				day: 13,
				name: "Cèdre",
				type: DayType.Arbre,
				wikipedia: "https://fr.wikipedia.org/wiki/Cèdre",
			},
			{
				day: 14,
				name: "Sapin",
				type: DayType.Arbre,
				wikipedia: "https://fr.wikipedia.org/wiki/Sapin",
			},
			{
				day: 15,
				name: "Chevreuil",
				type: DayType.Mammifère,
				wikipedia: "https://fr.wikipedia.org/wiki/Chevreuil",
			},
			{
				day: 16,
				name: "Ajonc",
				type: DayType.Végétal,
				wikipedia: "https://fr.wikipedia.org/wiki/Ulex",
			},
			{
				day: 17,
				name: "Cyprès",
				type: DayType.Arbre,
				wikipedia: "https://fr.wikipedia.org/wiki/Cyprès",
			},
			{
				day: 18,
				name: "Lierre",
				type: DayType.Végétal,
				wikipedia: "https://fr.wikipedia.org/wiki/Hedera",
			},
			{
				day: 19,
				name: "Sabine",
				type: DayType.Végétal,
				wikipedia: "https://fr.wikipedia.org/wiki/Juniperus_sabina",
			},
			{
				day: 20,
				name: "Hoyau",
				type: DayType.Outil,
				wikipedia: "https://fr.wikipedia.org/wiki/Hoyau",
			},
			{
				day: 21,
				name: "Érable sucré",
				type: DayType.Arbre,
				wikipedia: "https://fr.wikipedia.org/wiki/Érable_à_sucre",
			},
			{
				day: 22,
				name: "Bruyère",
				type: DayType.Végétal,
				wikipedia: "https://fr.wikipedia.org/wiki/Bruyère",
			},
			{
				day: 23,
				name: "Roseau",
				type: DayType.Végétal,
				wikipedia: "https://fr.wikipedia.org/wiki/Roseau",
			},
			{
				day: 24,
				name: "Oseille",
				type: DayType.Végétal,
				wikipedia: "https://fr.wikipedia.org/wiki/Rumex",
			},
			{
				day: 25,
				name: "Grillon",
				type: DayType.Insecte,
				wikipedia: "https://fr.wikipedia.org/wiki/Gryllidae",
			},
			{
				day: 26,
				name: "Pignon",
				type: DayType.Fruit,
				wikipedia: "https://fr.wikipedia.org/wiki/Pignon_(pin)",
			},
			{
				day: 27,
				name: "Liège",
				type: DayType.Végétal,
				wikipedia: "https://fr.wikipedia.org/wiki/Liège_(matériau)",
			},
			{
				day: 28,
				name: "Truffe",
				type: DayType.Champignon,
				wikipedia: "https://fr.wikipedia.org/wiki/Truffe_(champignon)",
			},
			{
				day: 29,
				name: "Olive",
				type: DayType.Fruit,
				wikipedia: "https://fr.wikipedia.org/wiki/Olive",
			},
			{
				day: 30,
				name: "Pelle",
				type: DayType.Outil,
				wikipedia: "https://fr.wikipedia.org/wiki/Pelle_(outil)",
			},
		]
	},
	{
		name: "Nivôse",
		image: "nivose.jpg",
		description: "Période de la neige",
		notes: [
			{
				title: 'Choix technique - Association de mot',
				content: 'Contrairement aux autres mois qui mettent en avant les végétaux, le mois de nivôse est consacrés aux matériaux terrestres.',
			},
			{
				title: 'Histoire - Rejet populaire',
				content: 'Le calendrier républicain n\'ayant pas su remplacer les nombreux jours fériés de la religion catholique, et les décades n\'octroyant qu\'un seul jour de repos pour neuf jours travaillés, contre un pour sept pour le semaines, peu voulaient l\'utiliser au quotidien.',
			},
			{
				title: 'Suffix saisonnier',
				content: 'Le suffixe "-ôse" des mois d\'hiver vient du latin "-osus" signifiant "qui est plein de, doté de".',
			},
			{
				title: 'Étymologie',
				content: 'Du latin nix, nivis « neige ».',
			},
		],
		days: [
			{
				day: 1,
				name: "Tourbe",
				type: DayType.Végétal,
				wikipedia: "https://fr.wikipedia.org/wiki/Tourbe",
			},
			{
				day: 2,
				name: "Houille",
				type: DayType.Minéral,
				wikipedia: "https://fr.wikipedia.org/wiki/Houille",
			},
			{
				day: 3,
				name: "Bitume",
				type: DayType.Minéral,
				wikipedia: "https://fr.wikipedia.org/wiki/Bitume",
			},
			{
				day: 4,
				name: "Soufre",
				type: DayType.Minéral,
				wikipedia: "https://fr.wikipedia.org/wiki/Soufre",
			},
			{
				day: 5,
				name: "Chien",
				type: DayType.Mammifère,
				wikipedia: "https://fr.wikipedia.org/wiki/Chien",
			},
			{
				day: 6,
				name: "Lave",
				type: DayType.Minéral,
				wikipedia: "https://fr.wikipedia.org/wiki/Lave",
			},
			{
				day: 7,
				name: "Terre végétale",
				type: DayType.Minéral,
				wikipedia: "https://fr.wikipedia.org/wiki/Humus",
			},
			{
				day: 8,
				name: "Fumier",
				type: DayType.Minéral,
				wikipedia: "https://fr.wikipedia.org/wiki/Fumier",
			},
			{
				day: 9,
				name: "Salpêtre",
				type: DayType.Minéral,
				wikipedia: "https://fr.wikipedia.org/wiki/Nitrate_de_potassium",
			},
			{
				day: 10,
				name: "Fléau",
				type: DayType.Outil,
				wikipedia: "https://fr.wikipedia.org/wiki/Fléau_(agriculture)",
			},
			{
				day: 11,
				name: "Granit",
				type: DayType.Minéral,
				wikipedia: "https://fr.wikipedia.org/wiki/Granit",
			},
			{
				day: 12,
				name: "Argile",
				type: DayType.Minéral,
				wikipedia: "https://fr.wikipedia.org/wiki/Argile",
			},
			{
				day: 13,
				name: "Ardoise",
				type: DayType.Minéral,
				wikipedia: "https://fr.wikipedia.org/wiki/Ardoise",
			},
			{
				day: 14,
				name: "Grès",
				type: DayType.Minéral,
				wikipedia: "https://fr.wikipedia.org/wiki/Grès_(géologie)",
			},
			{
				day: 15,
				name: "Lapin",
				type: DayType.Mammifère,
				wikipedia: "https://fr.wikipedia.org/wiki/Oryctolagus_cuniculus",
			},
			{
				day: 16,
				name: "Silex",
				type: DayType.Minéral,
				wikipedia: "https://fr.wikipedia.org/wiki/Silex",
			},
			{
				day: 17,
				name: "Marne",
				type: DayType.Minéral,
				wikipedia: "https://fr.wikipedia.org/wiki/Marne_(géologie)",
			},
			{
				day: 18,
				name: "Pierre à chaux",
				type: DayType.Minéral,
				wikipedia: "https://fr.wikipedia.org/wiki/Calcaire",
			},
			{
				day: 19,
				name: "Marbre",
				type: DayType.Minéral,
				wikipedia: "https://fr.wikipedia.org/wiki/Marbre",
			},
			{
				day: 20,
				name: "Van",
				type: DayType.Outil,
				wikipedia: "https://fr.wikipedia.org/wiki/Van_(agriculture)",
			},
			{
				day: 21,
				name: "Pierre à plâtre",
				type: DayType.Minéral,
				wikipedia: "https://fr.wikipedia.org/wiki/Gypse",
			},
			{
				day: 22,
				name: "Sel",
				type: DayType.Minéral,
				wikipedia: "https://fr.wikipedia.org/wiki/Chlorure_de_sodium",
			},
			{
				day: 23,
				name: "Fer",
				type: DayType.Métal,
				wikipedia: "https://fr.wikipedia.org/wiki/Fer",
			},
			{
				day: 24,
				name: "Cuivre",
				type: DayType.Métal,
				wikipedia: "https://fr.wikipedia.org/wiki/Cuivre",
			},
			{
				day: 25,
				name: "Chat",
				type: DayType.Mammifère,
				wikipedia: "https://fr.wikipedia.org/wiki/Chat",
			},
			{
				day: 26,
				name: "Étain",
				type: DayType.Métal,
				wikipedia: "https://fr.wikipedia.org/wiki/Étain",
			},
			{
				day: 27,
				name: "Plomb",
				type: DayType.Métal,
				wikipedia: "https://fr.wikipedia.org/wiki/Plomb",
			},
			{
				day: 28,
				name: "Zinc",
				type: DayType.Métal,
				wikipedia: "https://fr.wikipedia.org/wiki/Zinc",
			},
			{
				day: 29,
				name: "Mercure",
				type: DayType.Métal,
				wikipedia: "https://fr.wikipedia.org/wiki/Mercure_(chimie)",
			},
			{
				day: 30,
				name: "Crible",
				type: DayType.Outil,
				wikipedia: "https://fr.wikipedia.org/wiki/Tamis",
			},
		],
	},
	{
		name: "Pluviôse",
		image: "pluviose.jpg",
		description: "Période des pluies",
		notes: [
			{
				title: 'Choix technique - Association de mot',
				content: `Chaque jour de l'année est associé à un mote unique, plante, outil, animal ou minéral, au lieu des saints du calendrier grégorien. Cette nomenclature de 360 noms plus 5 ou 6 jours complémentaires fut créée par Fabre d'Églantine. Le type des mots est suggéré par une point de couleur:
<ul class="day-types-legend">
<li><div class="day-type day-type--végétal"></div>Végétal</li>
<li><div class="day-type day-type--animal"></div>Animal</li>
<li><div class="day-type day-type--minéral"></div>Minéral</li>
<li><div class="day-type day-type--outil"></div>Outil</li>
<li><div class="day-type day-type--fête"></div>Fête</li>
</ul>
`,
			},
			{
				title: 'Anecdote - Fleurs du mal',
				content: "Le nom de ce mois a été rendu célèbre par le sonnet de Charles Baudelaire Spleen I, des Fleurs du mal.",
			},
		],
		days: [
			{
				day: 1,
				name: "Lauréole",
				type: DayType.Végétal,
				wikipedia: "https://fr.wikipedia.org/wiki/Daphne_laureola",
			},
			{
				day: 2,
				name: "Mousse",
				type: DayType.Végétal,
				wikipedia: "https://fr.wikipedia.org/wiki/Bryophyta",
			},
			{
				day: 3,
				name: "Fragon",
				type: DayType.Végétal,
				wikipedia: "https://fr.wikipedia.org/wiki/Ruscus_aculeatus",
			},
			{
				day: 4,
				name: "Perce neige",
				type: DayType.Végétal,
				wikipedia: "https://fr.wikipedia.org/wiki/Perce-neige",
			},
			{
				day: 5,
				name: "Taureau",
				type: DayType.Mammifère,
				wikipedia: "https://fr.wikipedia.org/wiki/Taureau",
			},
			{
				day: 6,
				name: "Laurier thym",
				type: DayType.Végétal,
				wikipedia: "https://fr.wikipedia.org/wiki/Viorne_tin",
			},
			{
				day: 7,
				name: "Amadouvier",
				type: DayType.Végétal,
				wikipedia: "https://fr.wikipedia.org/wiki/Amadouvier",
			},
			{
				day: 8,
				name: "Mézéréon",
				type: DayType.Fleur,
				wikipedia: "https://fr.wikipedia.org/wiki/Bois-joli",
			},
			{
				day: 9,
				name: "Peuplier",
				type: DayType.Arbre,
				wikipedia: "https://fr.wikipedia.org/wiki/Peuplier",
			},
			{
				day: 10,
				name: "Cognée",
				type: DayType.Outil,
				wikipedia: "https://fr.wikipedia.org/wiki/Cognée",
			},
			{
				day: 11,
				name: "Ellébore",
				type: DayType.Fleur,
				wikipedia: "https://fr.wikipedia.org/wiki/Hellébore",
			},
			{
				day: 12,
				name: "Brocoli",
				type: DayType.Végétal,
				wikipedia: "https://fr.wikipedia.org/wiki/Brocoli",
			},
			{
				day: 13,
				name: "Laurier",
				type: DayType.Végétal,
				wikipedia: "https://fr.wikipedia.org/wiki/Laurus_nobilis",
			},
			{
				day: 14,
				name: "Avelinier",
				type: DayType.Arbre,
				wikipedia: "https://fr.wikipedia.org/wiki/Noisetier",
			},
			{
				day: 15,
				name: "Vache",
				type: DayType.Mammifère,
				wikipedia: "https://fr.wikipedia.org/wiki/Vache",
			},
			{
				day: 16,
				name: "Buis",
				type: DayType.Végétal,
				wikipedia: "https://fr.wikipedia.org/wiki/Buis",
			},
			{
				day: 17,
				name: "Lichen",
				type: DayType.Végétal,
				wikipedia: "https://fr.wikipedia.org/wiki/Lichen",
			},
			{
				day: 18,
				name: "If",
				type: DayType.Arbre,
				wikipedia: "https://fr.wikipedia.org/wiki/Taxus",
			},
			{
				day: 19,
				name: "Pulmonaire",
				type: DayType.Végétal,
				wikipedia: "https://fr.wikipedia.org/wiki/pulmonaria",
			},
			{
				day: 20,
				name: "Serpette",
				type: DayType.Outil,
				wikipedia: "https://fr.wikipedia.org/wiki/Serpette",
			},
			{
				day: 21,
				name: "Thlaspi",
				type: DayType.Végétal,
				wikipedia: "https://fr.wikipedia.org/wiki/Thlaspi",
			},
			{
				day: 22,
				name: "Thymèle",
				type: DayType.Végétal,
				wikipedia: "https://fr.wikipedia.org/wiki/Daphné_garou",
			},
			{
				day: 23,
				name: "Chiendent",
				type: DayType.Végétal,
				wikipedia: "https://fr.wikipedia.org/wiki/Chiendent",
			},
			{
				day: 24,
				name: "Trainasse",
				type: DayType.Végétal,
				wikipedia: "https://fr.wikipedia.org/wiki/Renouée_des_oiseaux",
			},
			{
				day: 25,
				name: "Lièvre",
				type: DayType.Mammifère,
				wikipedia: "https://fr.wikipedia.org/wiki/Lièvre",
			},
			{
				day: 26,
				name: "Guède",
				type: DayType.Végétal,
				wikipedia: "https://fr.wikipedia.org/wiki/Pastel_des_teinturiers",
			},
			{
				day: 27,
				name: "Noisetier",
				type: DayType.Arbre,
				wikipedia: "https://fr.wikipedia.org/wiki/Noisetier",
			},
			{
				day: 28,
				name: "Cyclamen",
				type: DayType.Fleur,
				wikipedia: "https://fr.wikipedia.org/wiki/Cyclamen",
			},
			{
				day: 29,
				name: "Chélidoine",
				type: DayType.Végétal,
				wikipedia: "https://fr.wikipedia.org/wiki/Chelidonium_majus",
			},
			{
				day: 30,
				name: "Traîneau",
				type: DayType.Outil,
				wikipedia: "https://fr.wikipedia.org/wiki/Traîneau",
			},
		],
	},
	{
		name: "Ventôse",
		image: "ventose.jpg",
		description: "Période des vents",
		notes: [
			{
				title: 'Histoire - Abolition',
				content: `<blockquote>Victorieuse dans son ambition de remodeler les structures de l’espace, par le système métrique, la Révolution a échoué dans sa tentative à l’égard de celle du temps.</blockquote>
<br/>
Napoléon Bonaparte abroge le calendrier républicain par le sénatus-consulte du <time>22 fructidor an XIII</time> (9 septembre 1805), avec effet au <time>1er janvier 1806</time> (11 nivôse an XIV). Le calendrier grégorien fut rétabli, marquant la fin d'une expérience de 12 ans, 2 mois et 27 jours.
<br/>
<br/>
L'une des raison était de faciliter les relations diplomatiques, car bien qu'originalement calqué sur la nature, l’universalisation de ce calendrier posait problèmes sous d’autres climats et d’autres latitudes.
<br/>
<br/>
Cette décision visait aussi à améliorer les relations avec l'Église catholique suite au Concordat de 1801 définissant les relations entre l'Église catholique et la République française.`
			}
		],
		days: [
			{
				day: 1,
				name: "Tussilage",
				type: DayType.Fleur,
				wikipedia: "https://fr.wikipedia.org/wiki/Tussilage",
			},
			{
				day: 2,
				name: "Cornouiller",
				type: DayType.Arbre,
				wikipedia: "https://fr.wikipedia.org/wiki/Cornus_(plante)",
			},
			{
				day: 3,
				name: "Violier",
				type: DayType.Végétal,
				wikipedia: "https://fr.wikipedia.org/wiki/Vélar",
			},
			{
				day: 4,
				name: "Troène",
				type: DayType.Végétal,
				wikipedia: "https://fr.wikipedia.org/wiki/Troène",
			},
			{
				day: 5,
				name: "Bouc",
				type: DayType.Mammifère,
				wikipedia: "https://fr.wikipedia.org/wiki/Bouc",
			},
			{
				day: 6,
				name: "Asaret",
				type: DayType.Végétal,
				wikipedia: "https://fr.wikipedia.org/wiki/Asaret",
			},
			{
				day: 7,
				name: "Alaterne",
				type: DayType.Végétal,
				wikipedia: "https://fr.wikipedia.org/wiki/Nerprun_alaterne",
			},
			{
				day: 8,
				name: "Violette",
				type: DayType.Fleur,
				wikipedia: "https://fr.wikipedia.org/wiki/Viola_(genre_végétal)",
			},
			{
				day: 9,
				name: "Marceau",
				type: DayType.Végétal,
				wikipedia: "https://fr.wikipedia.org/wiki/Saule_marsault",
			},
			{
				day: 10,
				name: "Bêche",
				type: DayType.Outil,
				wikipedia: "https://fr.wikipedia.org/wiki/Bêche",
			},
			{
				day: 11,
				name: "Narcisse",
				type: DayType.Fleur,
				wikipedia: "https://fr.wikipedia.org/wiki/Narcissus",
			},
			{
				day: 12,
				name: "Orme",
				type: DayType.Arbre,
				wikipedia: "https://fr.wikipedia.org/wiki/Orme",
			},
			{
				day: 13,
				name: "Fumeterre",
				type: DayType.Végétal,
				wikipedia: "https://fr.wikipedia.org/wiki/Fumeterre",
			},
			{
				day: 14,
				name: "Vélar",
				type: DayType.Végétal,
				wikipedia: "https://fr.wikipedia.org/wiki/Vélar",
			},
			{
				day: 15,
				name: "Chèvre",
				type: DayType.Mammifère,
				wikipedia: "https://fr.wikipedia.org/wiki/Chèvre",
			},
			{
				day: 16,
				name: "Épinard",
				type: DayType.Végétal,
				wikipedia: "https://fr.wikipedia.org/wiki/Épinard",
			},
			{
				day: 17,
				name: "Doronic",
				type: DayType.Fleur,
				wikipedia: "https://fr.wikipedia.org/wiki/Doronicum",
			},
			{
				day: 18,
				name: "Mouron",
				type: DayType.Végétal,
				wikipedia: "https://fr.wikipedia.org/wiki/Mouron_(flore)",
			},
			{
				day: 19,
				name: "Cerfeuil",
				type: DayType.Végétal,
				wikipedia: "https://fr.wikipedia.org/wiki/Cerfeuil_commun",
			},
			{
				day: 20,
				name: "Cordeau",
				type: DayType.Outil,
				wikipedia: "https://fr.wikipedia.org/wiki/Cordeau",
			},
			{
				day: 21,
				name: "Mandragore",
				type: DayType.Fleur,
				wikipedia: "https://fr.wikipedia.org/wiki/Mandragore",
			},
			{
				day: 22,
				name: "Persil",
				type: DayType.Végétal,
				wikipedia: "https://fr.wikipedia.org/wiki/Persil",
			},
			{
				day: 23,
				name: "Cochléaria",
				type: DayType.Végétal,
				wikipedia: "https://fr.wikipedia.org/wiki/Cochlearia",
			},
			{
				day: 24,
				name: "Pâquerette",
				type: DayType.Fleur,
				wikipedia: "https://fr.wikipedia.org/wiki/Pâquerette",
			},
			{
				day: 25,
				name: "Thon",
				type: DayType.Poisson,
				wikipedia: "https://fr.wikipedia.org/wiki/Thon",
			},
			{
				day: 26,
				name: "Pissenlit",
				type: DayType.Fleur,
				wikipedia: "https://fr.wikipedia.org/wiki/Pissenlit",
			},
			{
				day: 27,
				name: "Sylvie",
				type: DayType.Fleur,
				wikipedia: "https://fr.wikipedia.org/wiki/Anémone_sylvie",
			},
			{
				day: 28,
				name: "Capillaire",
				type: DayType.Végétal,
				wikipedia: "https://fr.wikipedia.org/wiki/Capillaire_de_Montpellier",
			},
			{
				day: 29,
				name: "Frêne",
				type: DayType.Arbre,
				wikipedia: "https://fr.wikipedia.org/wiki/Frêne",
			},
			{
				day: 30,
				name: "Plantoir",
				type: DayType.Outil,
				wikipedia: "https://fr.wikipedia.org/wiki/Plantoir",
			},
		],
	},
	{
		name: "Germinal",
		image: "germinal.jpg",
		description: "Période de la germination",
		notes: [
			{
				title: 'Anecdote - Germinal de Zola',
				content: 'Émile Zola choisit "Germinal" comme titre de son célèbre roman sur les mineurs (1885). Correspondant au retour du printemps et de l\'espoir, le mois de germinal incarne aussi les idées portées durant la Révolution française et présentes dans le livre, justice sociale, lutte politique, émancipation et dignité humaine.',
			},
			{
				title: 'Suffix saisonnier',
				content: 'Les mois du printemps terminent en -al, du latin -alis, suffixe adjectival',
			},
		],
		days: [
			{
				day: 1,
				name: "Primevère",
				type: DayType.Fleur,
				wikipedia: "https://fr.wikipedia.org/wiki/Primevère",
			},
			{
				day: 2,
				name: "Platane",
				type: DayType.Arbre,
				wikipedia: "https://fr.wikipedia.org/wiki/Platane",
			},
			{
				day: 3,
				name: "Asperge",
				type: DayType.Végétal,
				wikipedia: "https://fr.wikipedia.org/wiki/Asperge",
			},
			{
				day: 4,
				name: "Tulipe",
				type: DayType.Fleur,
				wikipedia: "https://fr.wikipedia.org/wiki/Tulipe",
			},
			{
				day: 5,
				name: "Poule",
				type: DayType.Oiseau,
				wikipedia: "https://fr.wikipedia.org/wiki/Poule",
			},
			{
				day: 6,
				name: "Bette",
				type: DayType.Végétal,
				wikipedia: "https://fr.wikipedia.org/wiki/Bette_(plante)",
			},
			{
				day: 7,
				name: "Bouleau",
				type: DayType.Arbre,
				wikipedia: "https://fr.wikipedia.org/wiki/Bouleau",
			},
			{
				day: 8,
				name: "Jonquille",
				type: DayType.Fleur,
				wikipedia: "https://fr.wikipedia.org/wiki/Jonquille",
			},
			{
				day: 9,
				name: "Aulne",
				type: DayType.Arbre,
				wikipedia: "https://fr.wikipedia.org/wiki/Aulne",
			},
			{
				day: 10,
				name: "Couvoir",
				type: DayType.Outil,
				wikipedia: "https://fr.wikipedia.org/wiki/Couveuse_(homonymie)",
			},
			{
				day: 11,
				name: "Pervenche",
				type: DayType.Fleur,
				wikipedia: "https://fr.wikipedia.org/wiki/Pervenche",
			},
			{
				day: 12,
				name: "Charme",
				type: DayType.Arbre,
				wikipedia: "https://fr.wikipedia.org/wiki/Charme",
			},
			{
				day: 13,
				name: "Morille",
				type: DayType.Végétal,
				wikipedia: "https://fr.wikipedia.org/wiki/Morille",
			},
			{
				day: 14,
				name: "Hêtre",
				type: DayType.Arbre,
				wikipedia: "https://fr.wikipedia.org/wiki/H%C3%AAtre",
			},
			{
				day: 15,
				name: "Abeille",
				type: DayType.Insecte,
				wikipedia: "https://fr.wikipedia.org/wiki/Abeille",
			},
			{
				day: 16,
				name: "Laitue",
				type: DayType.Végétal,
				wikipedia: "https://fr.wikipedia.org/wiki/Laitue",
			},
			{
				day: 17,
				name: "Mélèze",
				type: DayType.Arbre,
				wikipedia: "https://fr.wikipedia.org/wiki/M%C3%A9l%C3%A8ze",
			},
			{
				day: 18,
				name: "Ciguë",
				type: DayType.Végétal,
				wikipedia: "https://fr.wikipedia.org/wiki/Cigu%C3%AB",
			},
			{
				day: 19,
				name: "Radis",
				type: DayType.Racine,
				wikipedia: "https://fr.wikipedia.org/wiki/Radis",
			},
			{
				day: 20,
				name: "Ruche",
				type: DayType.Outil,
				wikipedia: "https://fr.wikipedia.org/wiki/Ruche",
			},
			{
				day: 21,
				name: "Gainier",
				type: DayType.Arbre,
				wikipedia: "https://fr.wikipedia.org/wiki/Arbre_de_Jud%C3%A9e",
			},
			{
				day: 22,
				name: "Romaine",
				type: DayType.Végétal,
				wikipedia: "https://fr.wikipedia.org/wiki/Laitue_romaine",
			},
			{
				day: 23,
				name: "Marronnier",
				type: DayType.Arbre,
				wikipedia: "https://fr.wikipedia.org/wiki/Aesculus_hippocastanum",
			},
			{
				day: 24,
				name: "Roquette",
				type: DayType.Végétal,
				wikipedia: "https://fr.wikipedia.org/wiki/Roquette_(plante)",
			},
			{
				day: 25,
				name: "Pigeon",
				type: DayType.Oiseau,
				wikipedia: "https://fr.wikipedia.org/wiki/Columba_(oiseau)",
			},
			{
				day: 26,
				name: "Lilas",
				type: DayType.Fleur,
				wikipedia: "https://fr.wikipedia.org/wiki/Syringa_vulgaris",
			},
			{
				day: 27,
				name: "Anémone",
				type: DayType.Fleur,
				wikipedia: "https://fr.wikipedia.org/wiki/Anémone",
			},
			{
				day: 28,
				name: "Pensée",
				type: DayType.Fleur,
				wikipedia: "https://fr.wikipedia.org/wiki/Viola_(genre_végétal)",
			},
			{
				day: 29,
				name: "Myrtille",
				type: DayType.Fruit,
				wikipedia: "https://fr.wikipedia.org/wiki/Myrtille",
			},
			{
				day: 30,
				name: "Greffoir",
				type: DayType.Outil,
				wikipedia: "https://fr.wikipedia.org/wiki/Greffoir",
			}
		]
	},
	{
		name: "Floréal",
		image: "floreal.jpg",
		description: "Période de l'épanouissement des fleurs",
		notes: [
			{
				title: 'Choix technique - Association de mot',
				content: `Dans le calendrier républicain, les jours sont principalement consacrés aux végétaux. Mais une structure se répète chaque mois :
<ul>
<li>Les quintidi sont consacrés aux animaux</li>
<li>Les décadi sont consacrés aux outils agricoles</li>
</ul>`,
			},
		],
		days: [
			{
				day: 1,
				name: "Rose",
				type: DayType.Fleur,
				wikipedia: "https://fr.wikipedia.org/wiki/Rose_(fleur)",
			},
			{
				day: 2,
				name: "Chêne",
				type: DayType.Arbre,
				wikipedia: "https://fr.wikipedia.org/wiki/Chêne",
			},
			{
				day: 3,
				name: "Fougère",
				type: DayType.Végétal,
				wikipedia: "https://fr.wikipedia.org/wiki/Filicophyta",
			},
			{
				day: 4,
				name: "Aubépine",
				type: DayType.Fleur,
				wikipedia: "https://fr.wikipedia.org/wiki/Aubépine",
			},
			{
				day: 5,
				name: "Rossignol",
				type: DayType.Oiseau,
				wikipedia: "https://fr.wikipedia.org/wiki/Rossignol",
			},
			{
				day: 6,
				name: "Ancolie",
				type: DayType.Fleur,
				wikipedia: "https://fr.wikipedia.org/wiki/Ancolie",
			},
			{
				day: 7,
				name: "Muguet",
				type: DayType.Fleur,
				wikipedia: "https://fr.wikipedia.org/wiki/Muguet_de_mai",
			},
			{
				day: 8,
				name: "Champignon",
				type: DayType.Champignon,
				wikipedia: "https://fr.wikipedia.org/wiki/Champignon",
			},
			{
				day: 9,
				name: "Hyacinthe",
				type: DayType.Fleur,
				wikipedia: "https://fr.wikipedia.org/wiki/Hyacinthus",
			},
			{
				day: 10,
				name: "Râteau",
				type: DayType.Outil,
				wikipedia: "https://fr.wikipedia.org/wiki/Râteau_(outil)",
			},
			{
				day: 11,
				name: "Rhubarbe",
				type:	DayType.Végétal,
				wikipedia: "https://fr.wikipedia.org/wiki/Rhubarbe",
			},
			{
				day: 12,
				name: "Sainfoin",
				type: DayType.Végétal,
				wikipedia: "https://fr.wikipedia.org/wiki/Onobrychis",
			},
			{
				day: 13,
				name: "Bâton-d'or",
				type: DayType.Végétal,
				wikipedia: "https://fr.wikipedia.org/wiki/Vélar",
			},
			{
				day: 14,
				name: "Chamérisier",
				type: DayType.Végétal,
				wikipedia: "https://fr.wikipedia.org/wiki/Lonicera_xylosteum",
			},
			{
				day: 15,
				name: "Ver à soie",
				type: DayType.Insecte,
				wikipedia: "https://fr.wikipedia.org/wiki/Bombyx_du_mûrier",
			},
			{
				day: 16,
				name: "Consoude",
				type: DayType.Végétal,
				wikipedia: "https://fr.wikipedia.org/wiki/Consoude",
			},
			{
				day: 17,
				name: "Pimprenelle",
				type: DayType.Végétal,
				wikipedia: "https://fr.wikipedia.org/wiki/Pimprenelle",
			},
			{
				day: 18,
				name: "Corbeille d'or",
				type: DayType.Végétal,
				wikipedia: "https://fr.wikipedia.org/wiki/Corbeille_d'or",
			},
			{
				day: 19,
				name: "Arroche",
				type: DayType.Végétal,
				wikipedia: "https://fr.wikipedia.org/wiki/Arroche_des_jardins",
			},
			{
				day: 20,
				name: "Sarcloir",
				type: DayType.Outil,
				wikipedia: "https://fr.wikipedia.org/wiki/Sarcloir",
			},
			{
				day: 21,
				name: "Statice",
				type: DayType.Végétal,
				wikipedia: "https://fr.wikipedia.org/wiki/Armérie_maritime",
			},
			{
				day: 22,
				name: "Fritillaire",
				type: DayType.Végétal,
				wikipedia: "https://fr.wikipedia.org/wiki/Fritillaire",
			},
			{
				day: 23,
				name: "Bourrache",
				type: DayType.Végétal,
				wikipedia: "https://fr.wikipedia.org/wiki/Bourrache",
			},
			{
				day: 24,
				name: "Valériane",
				type: DayType.Végétal,
				wikipedia: "https://fr.wikipedia.org/wiki/Valériane",
			},
			{
				day: 25,
				name: "Carpe",
				type: DayType.Poisson,
				wikipedia: "https://fr.wikipedia.org/wiki/Carpe_(poisson)",
			},
			{
				day: 26,
				name: "Fusain",
				type: DayType.Végétal,
				wikipedia: "https://fr.wikipedia.org/wiki/Fusain_d'Europe",
			},
			{
				day: 27,
				name: "Civette",
				type: DayType.Végétal,
				wikipedia: "https://fr.wikipedia.org/wiki/Ciboulette_commune",
			},
			{
				day: 28,
				name: "Buglosse",
				type: DayType.Végétal,
				wikipedia: "https://fr.wikipedia.org/wiki/Anchusa",
			},
			{
				day: 29,
				name: "Sénevé",
				type: DayType.Végétal,
				wikipedia: "https://fr.wikipedia.org/wiki/Moutarde_blanche",
			},
			{
				day: 30,
				name: "Houlette",
				type: DayType.Outil,
				wikipedia: "https://fr.wikipedia.org/wiki/Houlette_(agriculture)",
			}
		]
	},
	{
		name: "Prairial",
		image: "prairial.jpg",
		description: "Période des récoltes des prairies",
		notes: [
			{
				title: 'Histoire - Contexte',
				content: 'Les paysans constituaient 85% de la population française en 1793, ce qui explique l\'omniprésence des références agricoles dans le calendrier.'
			},
		],
		days: [
			{
				day: 1,
				name: "Luzerne",
				type: DayType.Végétal,
				wikipedia: "https://fr.wikipedia.org/wiki/Luzerne_cultivée",
			},
			{
				day: 2,
				name: "Hémérocalle",
				type: DayType.Végétal,
				wikipedia: "https://fr.wikipedia.org/wiki/Hémérocalle",
			},
			{
				day: 3,
				name: "Trèfle",
				type: DayType.Végétal,
				wikipedia: "https://fr.wikipedia.org/wiki/Trèfle",
			},
			{
				day: 4,
				name: "Angélique",
				type: DayType.Végétal,
				wikipedia: "https://fr.wikipedia.org/wiki/Angelica",
			},
			{
				day: 5,
				name: "Canard",
				type: DayType.Oiseau,
				wikipedia: "https://fr.wikipedia.org/wiki/Canard",
			},
			{
				day: 6,
				name: "Mélisse",
				type: DayType.Végétal,
				wikipedia: "https://fr.wikipedia.org/wiki/Mélisse_officinale",
			},
			{
				day: 7,
				name: "Fromental",
				type: DayType.Végétal,
				wikipedia: "https://fr.wikipedia.org/wiki/Arrhenatherum_elatius",
			},
			{
				day: 8,
				name: "Martagon",
				type: DayType.Fleur,
				wikipedia: "https://fr.wikipedia.org/wiki/Lis_martagon",
			},
			{
				day: 9,
				name: "Serpolet",
				type: DayType.Végétal,
				wikipedia: "https://fr.wikipedia.org/wiki/Serpolet",
			},
			{
				day: 10,
				name: "Faux",
				type: DayType.Outil,
				wikipedia: "https://fr.wikipedia.org/wiki/Faux_(outil)",
			},
			{
				day: 11,
				name: "Fraise",
				type: DayType.Fruit,
				wikipedia: "https://fr.wikipedia.org/wiki/Fraise",
			},
			{
				day: 12,
				name: "Bétoine",
				type: DayType.Fleur,
				wikipedia: "https://fr.wikipedia.org/wiki/Épiaire_officinale",
			},
			{
				day: 13,
				name: "Pois",
				type: DayType.Végétal,
				wikipedia: "https://fr.wikipedia.org/wiki/Pois_cultivé",
			},
			{
				day: 14,
				name: "Acacia",
				type: DayType.Arbre,
				wikipedia: "https://fr.wikipedia.org/wiki/Robinia_pseudoacacia",
			},
			{
				day: 15,
				name: "Caille",
				type: DayType.Oiseau,
				wikipedia: "https://fr.wikipedia.org/wiki/Caille",
			},
			{
				day: 16,
				name: "Œillet",
				type: DayType.Fleur,
				wikipedia: "https://fr.wikipedia.org/wiki/Œillet",
			},
			{
				day: 17,
				name: "Sureau",
				type: DayType.Végétal,
				wikipedia: "https://fr.wikipedia.org/wiki/Sureau",
			},
			{
				day: 18,
				name: "Pavot",
				type: DayType.Céréale,
				wikipedia: "https://fr.wikipedia.org/wiki/Pavot",
			},
			{
				day: 19,
				name: "Tilleul",
				type: DayType.Arbre,
				wikipedia: "https://fr.wikipedia.org/wiki/Tilia",
			},
			{
				day: 20,
				name: "Fourche",
				type: DayType.Outil,
				wikipedia: "https://fr.wikipedia.org/wiki/Fourche",
			},
			{
				day: 21,
				name: "Barbeau",
				type: DayType.Fleur,
				wikipedia: "https://fr.wikipedia.org/wiki/Cyanus_segetum",
			},
			{
				day: 22,
				name: "Camomille",
				type: DayType.Fleur,
				wikipedia: "https://fr.wikipedia.org/wiki/Camomille_romaine",
			},
			{
				day: 23,
				name: "Chèvrefeuille",
				type: DayType.Végétal,
				wikipedia: "https://fr.wikipedia.org/wiki/Chèvrefeuille",
			},
			{
				day: 24,
				name: "Caille-lait",
				type: DayType.Végétal,
				wikipedia: "https://fr.wikipedia.org/wiki/Gaillet",
			},
			{
				day: 25,
				name: "Tanche",
				type: DayType.Poisson,
				wikipedia: "https://fr.wikipedia.org/wiki/Tanche",
			},
			{
				day: 26,
				name: "Jasmin",
				type: DayType.Fleur,
				wikipedia: "https://fr.wikipedia.org/wiki/Jasmin",
			},
			{
				day: 27,
				name: "Verveine",
				type: DayType.Végétal,
				wikipedia: "https://fr.wikipedia.org/wiki/Verbena",
			},
			{
				day: 28,
				name: "Thym",
				type: DayType.Végétal,
				wikipedia: "https://fr.wikipedia.org/wiki/Thym",
			},
			{
				day: 29,
				name: "Pivoine",
				type: DayType.Fleur,
				wikipedia: "https://fr.wikipedia.org/wiki/Pivoine",
			},
			{
				day: 30,
				name: "Chariot",
				type: DayType.Outil,
				wikipedia: "https://fr.wikipedia.org/wiki/Chariot",
			}
		]
	},
	{
		name: "Messidor",
		image: "messidor.jpg",
		description: "Période des moissons",
		notes: [
			{
				title: 'Suffix saisonnier',
				content: 'Les mois d\'été terminent en -idor, du grec ancien δῶρον (dôron), « don »',
			},
			{
				title: 'Étymologie',
				content: "Du latin messis, « moisson »",
			},
		],
		days: [
			{
				day: 1,
				name: "Seigle",
				type: DayType.Céréale,
				wikipedia: "https://fr.wikipedia.org/wiki/Seigle",
			},
			{
				day: 2,
				name: "Avoine",
				type: DayType.Céréale,
				wikipedia: "https://fr.wikipedia.org/wiki/Avoine_cultivée",
			},
			{
				day: 3,
				name: "Oignon",
				type: DayType.Racine,
				wikipedia: "https://fr.wikipedia.org/wiki/Oignon",
			},
			{
				day: 4,
				name: "Véronique",
				type: DayType.Fleur,
				wikipedia: "https://fr.wikipedia.org/wiki/Véronique_(plante)",
			},
			{
				day: 5,
				name: "Mulet",
				type: DayType.Mammifère,
				wikipedia: "https://fr.wikipedia.org/wiki/Mulet",
			},
			{
				day: 6,
				name: "Romarin",
				type: DayType.Végétal,
				wikipedia: "https://fr.wikipedia.org/wiki/Romarin",
			},
			{
				day: 7,
				name: "Concombre",
				type: DayType.Fruit,
				wikipedia: "https://fr.wikipedia.org/wiki/Concombre",
			},
			{
				day: 8,
				name: "Échalote",
				type: DayType.Racine,
				wikipedia: "https://fr.wikipedia.org/wiki/Échalote",
			},
			{
				day: 9,
				name: "Absinthe",
				type: DayType.Végétal,
				wikipedia: "https://fr.wikipedia.org/wiki/Absinthe_(plante)",
			},
			{
				day: 10,
				name: "Faucille",
				type: DayType.Outil,
				wikipedia: "https://fr.wikipedia.org/wiki/Faucille",
			},
			{
				day: 11,
				name: "Coriandre",
				type: DayType.Végétal,
				wikipedia: "https://fr.wikipedia.org/wiki/Coriandre",
			},
			{
				day: 12,
				name: "Artichaut",
				type: DayType.Végétal,
				wikipedia: "https://fr.wikipedia.org/wiki/Artichaut",
			},
			{
				day: 13,
				name: "Giroflée",
				type: DayType.Fleur,
				wikipedia: "https://fr.wikipedia.org/wiki/Giroflée_des_murailles",
			},
			{
				day: 14,
				name: "Lavande",
				type: DayType.Fleur,
				wikipedia: "https://fr.wikipedia.org/wiki/Lavande",
			},
			{
				day: 15,
				name: "Chamois",
				type: DayType.Mammifère,
				wikipedia: "https://fr.wikipedia.org/wiki/Chamois",
			},
			{
				day: 16,
				name: "Tabac",
				type: DayType.Végétal,
				wikipedia: "https://fr.wikipedia.org/wiki/Tabac",
			},
			{
				day: 17,
				name: "Groseille",
				type: DayType.Fruit,
				wikipedia: "https://fr.wikipedia.org/wiki/Groseille",
			},
			{
				day: 18,
				name: "Gesse",
				type: DayType.Végétal,
				wikipedia: "https://fr.wikipedia.org/wiki/Lathyrus",
			},
			{
				day: 19,
				name: "Cerise",
				type: DayType.Fruit,
				wikipedia: "https://fr.wikipedia.org/wiki/Cerise",
			},
			{
				day: 20,
				name: "Parc",
				type: DayType.Outil,
				wikipedia: "https://fr.wikipedia.org/wiki/Parc",
			},
			{
				day: 21,
				name: "Menthe",
				type: DayType.Végétal,
				wikipedia: "https://fr.wikipedia.org/wiki/Menthe",
			},
			{
				day: 22,
				name: "Cumin",
				type: DayType.Végétal,
				wikipedia: "https://fr.wikipedia.org/wiki/Cumin",
			},
			{
				day: 23,
				name: "Haricot",
				type: DayType.Végétal,
				wikipedia: "https://fr.wikipedia.org/wiki/Haricot",
			},
			{
				day: 24,
				name: "Orcanète",
				type: DayType.Végétal,
				wikipedia: "https://fr.wikipedia.org/wiki/Orcanette_des_teinturiers",
			},
			{
				day: 25,
				name: "Pintade",
				type: DayType.Oiseau,
				wikipedia: "https://fr.wikipedia.org/wiki/Pintade",
			},
			{
				day: 26,
				name: "Sauge",
				type: DayType.Végétal,
				wikipedia: "https://fr.wikipedia.org/wiki/Sauge",
			},
			{
				day: 27,
				name: "Ail",
				type: DayType.Racine,
				wikipedia: "https://fr.wikipedia.org/wiki/ail_cultivé",
			},
			{
				day: 28,
				name: "Vesce",
				type: DayType.Végétal,
				wikipedia: "https://fr.wikipedia.org/wiki/Vicia",
			},
			{
				day: 29,
				name: "Blé",
				type: DayType.Céréale,
				wikipedia: "https://fr.wikipedia.org/wiki/Blé",
			},
			{
				day: 30,
				name: "Chalemie",
				type: DayType.Outil,
				wikipedia: "https://fr.wikipedia.org/wiki/Chalemie",
			},
		],
	},
	{
		name: "Thermidor",
		image: "thermidor.jpg",
		description: "Période des chaleurs",
		notes: [
			{
				title: 'À propos de thermidor',
				content: 'Dans le texte primitif, le second mois de l\'été s\'appelait non pas « thermidor » (du grec Thermê chaleur), mais « fervidor », du mot Fervidus, signifiant brûlant en latin.',
			},
		],
		days: [
			{
				day: 1,
				name: "Épeautre",
				type: DayType.Céréale,
				wikipedia: "https://fr.wikipedia.org/wiki/Épeautre",
			},
			{
				day: 2,
				name: "Bouillon-blanc",
				type: DayType.Végétal,
				wikipedia: "https://fr.wikipedia.org/wiki/Bouillon-blanc",
			},
			{
				day: 3,
				name: "Melon",
				type: DayType.Fruit,
				wikipedia: "https://fr.wikipedia.org/wiki/Melon_(plante)",
			},
			{
				day: 4,
				name: "Ivraie",
				type: DayType.Végétal,
				wikipedia: "https://fr.wikipedia.org/wiki/Ivraie",
			},
			{
				day: 5,
				name: "Bélier",
				type: DayType.Mammifère,
				wikipedia: "https://fr.wikipedia.org/wiki/Bélier",
			},
			{
				day: 6,
				name: "Prêle",
				type: DayType.Végétal,
				wikipedia: "https://fr.wikipedia.org/wiki/Equisetidae",
			},
			{
				day: 7,
				name: "Armoise",
				type: DayType.Végétal,
				wikipedia: "https://fr.wikipedia.org/wiki/Armoise",
			},
			{
				day: 8,
				name: "Carthame",
				type: DayType.Végétal,
				wikipedia: "https://fr.wikipedia.org/wiki/Carthame",
			},
			{
				day: 9,
				name: "Mûre",
				type: DayType.Fruit,
				wikipedia: "https://fr.wikipedia.org/wiki/Mûre_(fruit_de_la_ronce)",
			},
			{
				day: 10,
				name: "Arrosoir",
				type: DayType.Outil,
				wikipedia: "https://fr.wikipedia.org/wiki/Arrosoir",
			},
			{
				day: 11,
				name: "Panic",
				type: DayType.Céréale,
				wikipedia: "https://fr.wikipedia.org/wiki/Panic_(plante)",
			},
			{
				day: 12,
				name: "Salicorne",
				type: DayType.Végétal,
				wikipedia: "https://fr.wikipedia.org/wiki/Salicorne",
			},
			{
				day: 13,
				name: "Abricot",
				type: DayType.Fruit,
				wikipedia: "https://fr.wikipedia.org/wiki/Abricot",
			},
			{
				day: 14,
				name: "Basilic",
				type: DayType.Végétal,
				wikipedia: "https://fr.wikipedia.org/wiki/Basilic_(plante)",
			},
			{
				day: 15,
				name: "Brebis",
				type: DayType.Mammifère,
				wikipedia: "https://fr.wikipedia.org/wiki/Mouton",
			},
			{
				day: 16,
				name: "Guimauve",
				type: DayType.Végétal,
				wikipedia: "https://fr.wikipedia.org/wiki/Guimauve_officinale",
			},
			{
				day: 17,
				name: "Lin",
				type: DayType.Céréale,
				wikipedia: "https://fr.wikipedia.org/wiki/Lin_cultivé",
			},
			{
				day: 18,
				name: "Amande",
				type: DayType.Fruit,
				wikipedia: "https://fr.wikipedia.org/wiki/Amande",
			},
			{
				day: 19,
				name: "Gentiane",
				type: DayType.Fleur,
				wikipedia: "https://fr.wikipedia.org/wiki/Gentiane",
			},
			{
				day: 20,
				name: "Écluse",
				type: DayType.Outil,
				wikipedia: "https://fr.wikipedia.org/wiki/Écluse",
			},
			{
				day: 21,
				name: "Carline",
				type: DayType.Fleur,
				wikipedia: "https://fr.wikipedia.org/wiki/Carline",
			},
			{
				day: 22,
				name: "Câprier",
				type: DayType.Végétal,
				wikipedia: "https://fr.wikipedia.org/wiki/Câprier",
			},
			{
				day: 23,
				name: "Lentille",
				type: DayType.Céréale,
				wikipedia: "https://fr.wikipedia.org/wiki/Lentille_cultivée",
			},
			{
				day: 24,
				name: "Aunée",
				type: DayType.Végétal,
				wikipedia: "https://fr.wikipedia.org/wiki/Inula",
			},
			{
				day: 25,
				name: "Loutre",
				type: DayType.Mammifère,
				wikipedia: "https://fr.wikipedia.org/wiki/Loutre",
			},
			{
				day: 26,
				name: "Myrte",
				type: DayType.Fleur,
				wikipedia: "https://fr.wikipedia.org/wiki/Myrte",
			},
			{
				day: 27,
				name: "Colza",
				type: DayType.Céréale,
				wikipedia: "https://fr.wikipedia.org/wiki/Colza",
			},
			{
				day: 28,
				name: "Lupin",
				type: DayType.Végétal,
				wikipedia: "https://fr.wikipedia.org/wiki/Lupin",
			},
			{
				day: 29,
				name: "Coton",
				type: DayType.Végétal,
				wikipedia: "https://fr.wikipedia.org/wiki/Coton",
			},
			{
				day: 30,
				name: "Moulin",
				type: DayType.Outil,
				wikipedia: "https://fr.wikipedia.org/wiki/Moulin",
			},
		],
	},
	{
		name: "Fructidor",
		image: "fructidor.jpg",
		description: "Période des fruits",
		notes: [
		],
		days: [
			{
				day: 1,
				name: "Prune",
				type: DayType.Fruit,
				wikipedia: "https://fr.wikipedia.org/wiki/Prune",
			},
			{
				day: 2,
				name: "Millet",
				type: DayType.Céréale,
				wikipedia: "https://fr.wikipedia.org/wiki/Millet_(graminée)",
			},
			{
				day: 3,
				name: "Lycoperdon",
				type: DayType.Champignon,
				wikipedia: "https://fr.wikipedia.org/wiki/Vesse-de-loup",
			},
			{
				day: 4,
				name: "Escourgeon",
				type: DayType.Céréale,
				wikipedia: "https://fr.wikipedia.org/wiki/Escourgeon",
			},
			{
				day: 5,
				name: "Saumon",
				type: DayType.Poisson,
				wikipedia: "https://fr.wikipedia.org/wiki/Saumon",
			},
			{
				day: 6,
				name: "Tubéreuse",
				type: DayType.Fleur,
				wikipedia: "https://fr.wikipedia.org/wiki/Tubéreuse",
			},
			{
				day: 7,
				name: "Sucrion",
				type: DayType.Céréale,
				wikipedia: "https://fr.wikipedia.org/wiki/Escourgeon",
			},
			{
				day: 8,
				name: "Apocyn",
				type: DayType.Végétal,
				wikipedia: "https://fr.wikipedia.org/wiki/Asclepias_syriaca",
			},
			{
				day: 9,
				name: "Réglisse",
				type: DayType.Végétal,
				wikipedia: "https://fr.wikipedia.org/wiki/Réglisse",
			},
			{
				day: 10,
				name: "Échelle",
				type: DayType.Outil,
				wikipedia: "https://fr.wikipedia.org/wiki/Échelle_(outil)",
			},
			{
				day: 11,
				name: "Pastèque",
				type: DayType.Fruit,
				wikipedia: "https://fr.wikipedia.org/wiki/Pastèque",
			},
			{
				day: 12,
				name: "Fenouil",
				type: DayType.Végétal,
				wikipedia: "https://fr.wikipedia.org/wiki/Fenouil",
			},
			{
				day: 13,
				name: "Épine-vinette",
				type: DayType.Végétal,
				wikipedia: "https://fr.wikipedia.org/wiki/Épine-vinette",
			},
			{
				day: 14,
				name: "Noix",
				type: DayType.Fruit,
				wikipedia: "https://fr.wikipedia.org/wiki/Noix",
			},
			{
				day: 15,
				name: "Truite",
				type: DayType.Poisson,
				wikipedia: "https://fr.wikipedia.org/wiki/Truite",
			},
			{
				day: 16,
				name: "Citron",
				type: DayType.Fruit,
				wikipedia: "https://fr.wikipedia.org/wiki/Citron",
			},
			{
				day: 17,
				name: "Cardère",
				type: DayType.Végétal,
				wikipedia: "https://fr.wikipedia.org/wiki/Cardère_sauvage",
			},
			{
				day: 18,
				name: "Nerprun",
				type: DayType.Végétal,
				wikipedia: "https://fr.wikipedia.org/wiki/Nerprun",
			},
			{
				day: 19,
				name: "Tagette",
				type: DayType.Fleur,
				wikipedia: "https://fr.wikipedia.org/wiki/Tagetes",
			},
			{
				day: 20,
				name: "Hotte",
				type: DayType.Outil,
				wikipedia: "https://fr.wikipedia.org/wiki/Panier",
			},
			{
				day: 21,
				name: "Églantier",
				type: DayType.Arbre,
				wikipedia: "https://fr.wikipedia.org/wiki/Rosa_canina",
			},
			{
				day: 22,
				name: "Noisette",
				type: DayType.Fruit,
				wikipedia: "https://fr.wikipedia.org/wiki/Noisette",
			},
			{
				day: 23,
				name: "Houblon",
				type: DayType.Céréale,
				wikipedia: "https://fr.wikipedia.org/wiki/Houblon",
			},
			{
				day: 24,
				name: "Sorgho",
				type: DayType.Céréale,
				wikipedia: "https://fr.wikipedia.org/wiki/Sorgo_commun",
			},
			{
				day: 25,
				name: "Écrevisse",
				type: DayType.Poisson,
				wikipedia: "https://fr.wikipedia.org/wiki/Écrevisse",
			},
			{
				day: 26,
				name: "Bigarade",
				type: DayType.Fruit,
				wikipedia: "https://fr.wikipedia.org/wiki/Bigaradier",
			},
			{
				day: 27,
				name: "Verge d'or",
				type: DayType.Végétal,
				wikipedia: "https://fr.wikipedia.org/wiki/Solidago",
			},
			{
				day: 28,
				name: "Maïs",
				type: DayType.Fruit,
				wikipedia: "https://fr.wikipedia.org/wiki/Maïs",
			},
			{
				day: 29,
				name: "Marron",
				type: DayType.Fruit,
				wikipedia: "https://fr.wikipedia.org/wiki/Marron_(fruit)",
			},
			{
				day: 30,
				name: "Panier",
				type: DayType.Outil,
				wikipedia: "https://fr.wikipedia.org/wiki/Panier",
			},
		],
	},
	{
		name: "Jours complémentaires (Sans-culottides)",
		image: "sans_culottes.jpg",
		"image_description": "Jean-Baptiste Lesueur, Sans-culottes en armes",
		description: "",
		notes: [
			{
				title: 'Choix technique - Jours complémentaires',
				content: "Ces jours complémentaires sont placés après le dernier mois de l'année, fructidor, afin de faire correspondre le jour de l'an avec le passage de l'équinoxe d'automne au méridien de Paris. Ces 5 ou 6 jours étaient chômés.",
			},
			{
				title: 'Choix technique - Années sextiles',
				content: "Lors des années sextiles, un sixème jours complémentaire apparait, le jour de la révolution.",
			},
			{
				title: 'À propos des jours complémentaires',
				content: "Initialement nommés sans-culottides (par référence aux sans-culottes) par le décret du 4 frimaire an II, ils furent rapidement rebaptisés jours complémentaires par un nouveau décret du 7 fructidor an III.",
			},
		],
		days: [
			{
				day: 1,
				name: "Jour de la Vertu",
				type: DayType.Fête,
				wikipedia: "https://fr.wikipedia.org/wiki/Jour_de_la_vertu",
			},
			{
				day: 2,
				name: "Jour du Génie",
				type: DayType.Fête,
				wikipedia: "https://fr.wikipedia.org/wiki/Jour_du_g%C3%A9nie",
			},
			{
				day: 3,
				name: "Jour du Travail",
				type: DayType.Fête,
				wikipedia: "https://fr.wikipedia.org/wiki/Jour_du_travail",
			},
			{
				day: 4,
				name: "Jour de l'Opinion",
				type: DayType.Fête,
				wikipedia: "https://fr.wikipedia.org/wiki/Jour_de_l%27opinion",
			},
			{
				day: 5,
				name: "Jour des Récompenses",
				type: DayType.Fête,
				wikipedia: "https://fr.wikipedia.org/wiki/Jour_des_r%C3%A9compenses",
			},
			{
				day: 6,
				name: "Jour de la Révolution",
				type: DayType.Fête,
				wikipedia: "https://fr.wikipedia.org/wiki/Jour_de_la_R%C3%A9volution",
			},
		],
	},
] satisfies Calendar